/** @type {import('tailwindcss').Config} */
module.exports = {
    // NOTE: Update this to include the paths to all files that contain Nativewind classes.
    content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}", "./screens/**/*.{js,jsx,ts,tsx}"],
    presets: [require("nativewind/preset")],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                primary: {
                    50: "#eff6ff",
                    100: "#dbeafe",
                    200: "#bfdbfe",
                    300: "#93c5fd",
                    400: "#60a5fa",
                    500: "#3b82f6",
                    600: "#2563eb",
                    700: "#1d4ed8",
                    800: "#1e40af",
                    900: "#1e3a8a",
                },
                background: "#ffffff",
                surface: "#f8fafc",
                text: "#1f2937",
                "text-secondary": "#6b7280",
                border: "#e5e7eb",
                dark: {
                    background: "#18181b",
                    surface: "#27272a",
                    text: "#f4f4f5",
                    "text-secondary": "#a1a1aa",
                    border: "#3f3f46",
                },
                // رنگ‌های Labels - حالت لایت
                labels: {
                    primary: "#000000",
                    secondary: "rgba(60, 60, 67, 0.60)",
                    tertiary: "rgba(60, 60, 67, 0.30)",
                    quaternary: "rgba(60, 60, 67, 0.18)",
                },
                // رنگ‌های Labels - حالت دارک
                "labels-dark": {
                    primary: "#ffffff",
                    secondary: "rgba(235, 235, 245, 0.60)",
                    tertiary: "rgba(235, 235, 245, 0.30)",
                    quaternary: "rgba(235, 235, 245, 0.18)",
                },
                system: {
                    red: "#FF3B30",
                    orange: "#FF9500",
                    yellow: "#FC0",
                    green: "#34C759",
                    mint: "#00C7BE",
                    teal: "#30B0C7",
                    cyan: "#32ADE6",
                    blue: "#007AFF",
                    indigo: "#5856D6",
                    purple: "#AF52DE",
                    pink: "#FF2D55",
                    brown: "#A2845E",
                    black: "#000",
                    gray: "#8E8E93",
                    gray2: "#AEAEB2",
                    gray3: "#C7C7CC",
                    gray4: "#D1D1D6",
                    gray5: "#E5E5EA",
                    gray6: "#F2F2F7",
                    white: "#ffffff",
                },
                "system-dark": {
                    red: "#FF453A",
                    orange: "#FF9F0A",
                    yellow: "#FFD60A",
                    green: "#30D158",
                    mint: "#63E6E2",
                    teal: "#40CBE0",
                    cyan: "#64D2FF",
                    blue: "#0A84FF",
                    indigo: "#5E5CE6",
                    purple: "#BF5AF2",
                    pink: "#FF375F",
                    brown: "#AC8E68",
                    black: "#000",
                    gray: "#8E8E93",
                    gray2: "#636366",
                    gray3: "#48484A",
                    gray4: "#3A3A3C",
                    gray5: "#2C2C2E",
                    gray6: "#1C1C1E",
                    white: "#ffffff",
                },
            },
        },
    },
    plugins: [],
};
