import Logo from "./Logo.svg";
export { default as AvatarIcon } from "./Avatar.svg";
export { default as CameraIcon } from "./Camera.svg";
export { default as ChevronLeftIcon } from "./ChevronLeft.svg";
export { default as ClearIcon } from "./Clear.svg";
export { default as DictationIcon } from "./Dictation.svg";
export { default as EyeInvisibleIcon } from "./EyeInvisible.svg";
export { default as EyeVisibleIcon } from "./Eyevisible.svg";
export { default as GalleryWideIcon } from "./galleryWide.svg";
export { default as MenuIcon } from "./Menu.svg";
export { default as PlusIcon } from "./Plus.svg";
export { default as PlusBoldIcon } from "./PlusBold.svg";
export { default as SearchGlyphIcon } from "./SearchGlyph.svg";
export { default as AestheticIcon } from "./SPECIALTIES/aesthetic.svg";
export { default as CosmeticSurgeryIcon } from "./SPECIALTIES/cosmetic_surgery.svg";
export { default as DentistryIcon } from "./SPECIALTIES/dentistry.svg";
export { default as DermatologyIcon } from "./SPECIALTIES/dermatology.svg";
export { default as GeneralPracticeIcon } from "./SPECIALTIES/general_practice.svg";
export { default as OrthodonticsIcon } from "./SPECIALTIES/orthodontics.svg";
export { default as AppleIcon } from "./Symbol/applelogo.svg";
export { default as GoogleIcon } from "./Symbol/googleLogo.svg";
export { default as ThreeDotsIcon } from "./ThreeDots.svg";
export { Logo as WelcomeLogo };
